name: Proposta di modifica
description: Suggerisci un aggiornamento
title: "Proposta: "
body:
  - type: input
    id: termine
    attributes:
      label: Termine da aggiungere
    validations:
      required: true

  - type: textarea
    id: dettagli
    attributes:
      label: Dettagli della nuova voce
      description: Descrivi che cosa dovrebbe contenere la nuova voce.
    validations:
      required: true

  - type: textarea
    id: motivazione
    attributes:
      label: Motivazione
      description: Spiega perché il nuovo termine dovrebbe essere aggiunto al tesauro.
    validations:
      required: true

  - type: textarea
    id: fonti
    attributes:
      label: Fonti
      description: Inserisci titolo, autore o ente e collegamento alla fonte.
    validations:
      required: true
