<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tesauro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="voce" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="termineEN" type="xs:string"/>
              <xs:element name="traduzioneIT" type="xs:string"/>
              <xs:element name="definizioneEN" type="xs:string"/>
              <xs:element name="bt" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="nt" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="rt" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="uf" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="fonte" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
